[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "MIT"

[lib]
name = "iota_client"
path = "lib.rs"

[dependencies]
reqwest = { version = "0.10.6", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.12"
iota-bundle-preview = "0.1"
iota-ternary-preview = "0.1"
iota-signing-preview = "0.1"
iota-crypto-preview = "0.1"
iota-conversion = { version = "0.5.1", path = "../iota-conversion" }
once_cell = "1.4.0"
smol = {version = "0.1.18", features = ["tokio02"], optional = true }

[dev-dependencies]
anyhow = "1.0.31"
smol = {version = "0.1.18", features = ["tokio02"] }
smol-potat = "0.3.3"

[features]
quorum = ["smol"]
wasm = ["chrono/wasmbind"]

[[test]]
name = "quorum"
required-features = ["quorum"]