[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[dependencies]
bee-transaction = { git = "https://github.com/Alex6323/bee-p.git" }
bee-ternary = { version = "0.3.1-alpha", git = "https://github.com/iotaledger/bee.git", branch = "dev", features = ["serde1"] }
bee-signing = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-signing-ext = { git = "https://github.com/wusyong/bee-p.git", branch = "sign-ext" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
reqwest = { version = "0.10.6", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
chrono = "0.4.12"
tokio = "0.2.22"